//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testXampp
{
    using System;
    using System.Collections.Generic;
    
    public partial class operatiune
    {
        public int id { get; set; }
        public Nullable<System.DateTime> data_intrare { get; set; }
        public Nullable<System.DateTime> data_iesire { get; set; }
        public int pret { get; set; }
        public int Angajat_id { get; set; }
        public int listaOperatiuni_id { get; set; }
        public string client_username { get; set; }
    
        public virtual angajat angajat { get; set; }
        public virtual client client { get; set; }
        public virtual listaoperatiuni listaoperatiuni { get; set; }
        public virtual profit profit { get; set; }
    }
}
