//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testXampp
{
    using System;
    using System.Collections.Generic;
    
    public partial class profit
    {
        public Nullable<int> pret { get; set; }
        public Nullable<System.DateTime> dataOp { get; set; }
        public int operatiune_id { get; set; }
    
        public virtual operatiune operatiune { get; set; }
    }
}
